### ISSUE TITLE
Login attempt failed error message logged in HA every time THFHA starts

### ISSUE THREAD

**Issue by advisorgee** [jimmyeao/THFHA-V1.0a#14]
Steps to reproduce
Perform initial setup; long lived access token generated, and tested OK
Start THFHA
Login Attempt failed message appears in notifications
Text of full log:

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:82
Integration: HTTP (documentation, issues)
First occurred: 5:42:38 PM (98 occurrences)
Last logged: 6:03:42 PM

Login attempt or request with invalid authentication from laptop (192.168.2.102). Requested URL: '/api/states/sensor.thfha_camera'. (None)
Login attempt or request with invalid authentication from laptop (192.168.2.102). Requested URL: '/api/states/sensor.thfha_microphone'. (None)
Login attempt or request with invalid authentication from laptop (192.168.2.102). Requested URL: '/api/states/sensor.thfha_blurred'. (None)
Login attempt or request with invalid authentication from laptop (192.168.2.102). Requested URL: '/api/states/sensor.thfha_hand'. (None)
Login attempt or request with invalid authentication from laptop (192.168.2.102). Requested URL: '/api/states/sensor.thfha_recording'. (None)

Everything does seem to work though.

Additional Details:
MQTT is configured (and working)
I'm running
HA: 2023.3.4
Supervisor: 2023.03.01
Operating System: 9.5
Frontend: 20230309.0 - latest
Windows 10

**Comment by jimmyeao** [comment]
Thanks for the info - Ive pushed a fix here: https://github.com/jimmyeao/THFHA-V1.0a/releases/tag/v1.1.0.610

**Comment by jimmyeao** [comment]
just to add, please pull latest version, MQTT was still bugged if you didn't specify the port
